sudo: required
language: java

services:
  -docker

before_install:
  - docker build -t carlad/sinatra .
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; ant;"
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; ant test"
script:
 - ant;
 - ant test;
